# Generated by Django 4.1.4 on 2023-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TimeField(null=True)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('date_modified', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('items', models.TimeField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
