# Generated by Django 4.1.5 on 2023-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_remove_item_list_alter_item_itemname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Title of the post', max_length=100)),
                ('body', models.TextField(help_text='Enter the content of the post', max_length=3000)),
                ('visibility', models.IntegerField(default=0, help_text='Enter 1 for visible, and any other number for hidden')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopList',
        ),
    ]
